baseURL: http://blog.mgechev.com/
disablePathToLower: true
languageCode: en-us
title: Minko Gechev's blog
googleAnalytics: "UA-18060688-3"
theme: "minimalist"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsUseClasses: true

outputFormats:
  RSS:
    baseName: "feed"

params:
  bio: "Co-founder & CTO at <a href=\"https://rhyme.com\">Rhyme.com</a>"
  event: "Articles about computer science, Angular, JavaScript, and compilers."
  author: "Minko Gechev"
  twitter: mgechev
  enableRSS: true
  enableGoogleAnalytics: true
  enableDisqus: true
  disqusShortname: mgechev
  socialIconStyle: ""
  iconFont: "font-awesome"
  archive: "Posts"

  selectedTalks:
    - title: "Mad Science with the Angular Compiler"
      event: AngularUP, Tel Aviv, Israel
      date: 25th of June, 2017
      slides: https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler
      video: https://www.youtube.com/watch?v=E707WJakn7A
      flag: ğŸ‡®ğŸ‡±
    - title: "Angular Performance Checklist"
      event: ngcruise, cruise ship, Bahamas
      date: 31st May, 2017
      video: https://www.youtube.com/watch?v=p9vT0W31ym8
      slides: https://speakerdeck.com/mgechev/angular-performance-checklist-1
      flag: ğŸ‡§ğŸ‡¸
    - title: "Automated Angular 2 Style Checking with Codelyzer"
      event: ng-conf (Salt Lake City, Utah, United States)
      date: 6th of May, 2016
      video: https://youtu.be/bci-Z6nURgE
      slides: https://speakerdeck.com/mgechev/automated-angular-2-style-checking-with-codelyzer
      flag: ğŸ‡ºğŸ‡¸

  talks:
    - title: "Faster Angular Applications"
      event: NgAtlanta, Atlanta, Georgia, USA
      date: 1st of February, 2018
      slides: https://speakerdeck.com/mgechev/faster-angular-applications
      flag: ğŸ‡ºğŸ‡¸
    - title: "Mad Science with the Angular Compiler (BG)"
      event: Dreamix, Sofia, Bulgaria
      date: 12th of January, 2018
      video: https://www.youtube.com/watch?v=Pe6OC0Qe7ZY
      slides: https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler
      flag: ğŸ‡§ğŸ‡¬
    - title: "Faster Angular Applications"
      event: HolyJS, Moscow, Russia
      date: 10th of December, 2017
      slides: https://speakerdeck.com/mgechev/faster-angular-applications
      eventLink: https://holyjs-moscow.ru/en/talks/3hmyldgekuymaycqcykq60/
      flag: ğŸ‡·ğŸ‡º
    - title: "Angular Performance Checklist"
      event: NG-COLOMBIA, online
      date: 18th of November, 2017
      video: https://www.youtube.com/watch?v=Rl4FX8cwHks&feature=youtu.be&t=3h28m29s
      slides: https://speakerdeck.com/mgechev/angular-performance-checklist-1
      eventLink: http://ng-colombia.org/
      flag: ğŸ‡¨ğŸ‡´
    - title: "Fast & /Fu(nctional|rious)/"
      event: Tesla Motors, California, United States
      date: 15th of November, 2017
      eventLink: https://tesla.com/
      flag: ğŸ‡ºğŸ‡¸
    - title: "Purely Fast"
      event: AngularConnect, London, United Kingdom
      date: 7th of November, 2017
      eventLink: https://www.angularconnect.com/2017/sessions/#s-669
      slides: https://speakerdeck.com/mgechev/purely-fast
      video: https://www.youtube.com/watch?v=ukErcJDjR_Y
      flag: ğŸ‡¬ğŸ‡§
    - title: "Angular Performance Checklist"
      event: Bay Fest, San Francisco, California
      date: 28th of October, 2017
      eventLink: https://bayfest2017.com/
      slides: https://speakerdeck.com/mgechev/angular-performance-checklist-1
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular Performance Checklist"
      event: Angular Dev Summit, online
      date: 11th of September, 2017
      eventLink: https://angulardevsummit.com/
      slides: https://speakerdeck.com/mgechev/angular-performance-checklist-1
      flag: ğŸŒ
    - title: "Angular Performance Checklist"
      event: ngHouston, online
      date: 18th of August, 2017
      eventLink: https://www.meetup.com/ngHouston/events/xmmkbnywlbwb/
      video: https://www.youtube.com/watch?v=esDKcn_1aic
      slides: https://speakerdeck.com/mgechev/angular-performance-checklist-1
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular Unplugged Q&A session"
      event: Q&amp;A session organized for the Bulgarian JavaScript community, Sofia, Bulgaria
      date: 13th of July, 2017
      slides: https://speakerdeck.com/mgechev/angular-unplugged
      flag: ğŸ‡§ğŸ‡¬
    - title: "Mad Science with the Angular Compiler"
      event: AngularUP, Tel Aviv, Israel
      date: 25th of June, 2017
      slides: https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler
      video: https://www.youtube.com/watch?v=E707WJakn7A
      flag: ğŸ‡®ğŸ‡±
    - title: "Angular Performance Checklist"
      event: ngcruise, cruise ship, Bahamas
      date: 31st May, 2017
      video: https://www.youtube.com/watch?v=p9vT0W31ym8
      slides: https://speakerdeck.com/mgechev/angular-performance-checklist-1
      flag: ğŸ‡§ğŸ‡¸
    - title: "Mad Science with the Angular Compiler"
      event: Angular Bolivia (online)
      date: 30th of April, 2017
      slides: https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler
      flag: ğŸ‡§ğŸ‡´
    - title: "Mad Science with the Angular Compiler"
      event: ng-conf, Salt Lake City, Utah
      date: 5th of April, 2017
      video: https://www.youtube.com/watch?v=tBV4IQwPssU
      slides: https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler
      flag: ğŸ‡ºğŸ‡¸
    - title: "Linting Angular"
      event: Modern Web, Mountain View, California
      date: 9th of March 2017
      slides: https://speakerdeck.com/mgechev/linting-angular-1
      video: https://www.youtube.com/watch?v=-rhLjl3_y7U
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular as Integrated Development Platform"
      event: Angular Sofia, Sofia, Bulgaria
      date: 12th of January 2017
      slides: https://speakerdeck.com/mgechev/angular-as-integrated-development-platform
      flag: ğŸ‡§ğŸ‡¬
    - title: "Scalable Application Architecture"
      event: ng-be, Ghent, Belgium
      date: 9th of December 2016
      slides: https://speakerdeck.com/mgechev/scalable-application-architecture
      video: https://www.youtube.com/watch?v=gtOPAj9_FSM
      flag: ğŸ‡§ğŸ‡ª
    - title: "Building Angular App for Production"
      event: SoCal CodeCamp, USC, Los Angeles
      date: 12th of November 2016
      slides: https://speakerdeck.com/mgechev/building-an-angular-app-for-production
      flag: ğŸ‡ºğŸ‡¸
    - title: "Building Angular App for Production"
      event: Angular Orange County, Google, Orange County
      date: 10th of November 2016
      slides: https://speakerdeck.com/mgechev/building-an-angular-app-for-production
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular Toolset Support"
      event: Connect.Tech, Atlanta, Georgia
      date: 22nd of October 2016
      slides: https://speakerdeck.com/mgechev/angular-toolset-support
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular Performance Checklist"
      event: Connect.Tech, Atlanta, Georgia
      date: 21st of October 2016
      slides: https://speakerdeck.com/mgechev/angular-performance-checklist
      flag: ğŸ‡ºğŸ‡¸
    - title: "Linting Angular"
      event: South Bay JavaScript, Mountain View, California
      date: 12th of October 2016
      slides: https://speakerdeck.com/mgechev/linting-angular
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular 2 Toolset Support"
      event: Capgemini Webinar (online)
      date: 26th of May, 2016
      slides: https://speakerdeck.com/mgechev/angular-2-toolset-support
      flag: ğŸ‡®ğŸ‡³
    - title: "Integrated Web Stack with Angular 2"
      event: xlr8con (Sofia, Bulgaria)
      date: 14th of May, 2016
      slides: https://speakerdeck.com/mgechev/integrated-web-stack-with-angular-2
      flag: ğŸ‡§ğŸ‡¬
    - title: "Automated Angular 2 Style Checking with Codelyzer"
      event: ng-conf (Salt Lake City, Utah, United States)
      date: 6th of May, 2016
      video: https://youtu.be/bci-Z6nURgE
      slides: https://speakerdeck.com/mgechev/automated-angular-2-style-checking-with-codelyzer
      flag: ğŸ‡ºğŸ‡¸
    - title: "Scalable Angular 2 Application Architecture"
      event: FDConf (Minsk, Belarus)
      date: 16th of April, 2016
      slides: https://speakerdeck.com/mgechev/scalable-angular-2-application-architecture
      flag: ğŸ‡§ğŸ‡¾
    - title: "Angular 2 - Quick Web Start"
      event: "Angular 2 â¤ NativeScript (Sofia, Bulgaria)"
      date: 10th of March, 2016
      slides: https://speakerdeck.com/mgechev/angular-2-quick-web-start
      flag: ğŸ‡§ğŸ‡¬
    - title: "Building Universal Applications with Angular 2"
      event: ITWeekend 2015 (Sofia, Bulgaria),
      date: November, 2015
      slides: https://speakerdeck.com/mgechev/building-universal-applications-with-angular-2
      flag: ğŸ‡§ğŸ‡¬
    - title: "Building Universal Applications with Angular 2"
      event: OpenFest 2015 (Sofia, Bulgaria)
      date: November, 2015
      slides: https://speakerdeck.com/mgechev/building-universal-applications-with-angular-2
      video: https://www.youtube.com/watch?v=mVuR7Uld2Og
      flag: ğŸ‡§ğŸ‡¬
    - title: "Building Universal Applications with Angular 2"
      event: JSTalks 2015 (Sofia, Bulgaria).
      date: November, 2015
      slides: https://speakerdeck.com/mgechev/building-universal-applications-with-angular-2
      flag: ğŸ‡§ğŸ‡¬
    - title: "Cutting Angularâ€™s Crosscuts"
      event: AngularConnect, London, United Kingdom
      date: 21st of October, 2015
      slides: https://speakerdeck.com/mgechev/cutting-angulars-crosscuts
      video: https://www.youtube.com/watch?v=C6e6-31HD5A
      flag: ğŸ‡¬ğŸ‡§
    - title: "Immutable.js with Angular"
      event: AngularAir Podcast (online)
      date: 22nd of September, 2015
      video: https://www.youtube.com/watch?v=gN1K1hE9v4g
      eventLink: http://angular-air.com/
      flag: ğŸŒ
    - title: "Single-Page Applications: Challenges"
      event: IT Weekend, Kiev, Ukraine,
      date: 12th of September, 2015
      slides: https://speakerdeck.com/mgechev/single-page-applications-challenges
      eventLink: http://ukraine.itweekend.ua/en/
      flag: ğŸ‡ºğŸ‡¦
    - title: "Bringing Immutability to Angular"
      event: Front-end Weekend (online)
      date: 16th of August, 2015
      slides: https://speakerdeck.com/mgechev/bringing-immutability-to-angular
      eventLink: http://frontendweekend.uwcua.com/
      flag: ğŸŒ
    - title: "Immutability with Angular with Minko Gechev"
      event: Adventures in Angular Podcast (online)
      date: 29th of July, 2015
      video: http://devchat.tv/adventures-in-angular/054-aia-immutability-with-angular-with-minko-gechev
      eventLink: http://adventuresinangular.com/
      flag: ğŸŒ
    - title: "Introduction to Angular 2"
      event: Webloz Edge, Burgas, Bulgaria
      date: 29th of June, 2015
      slides: https://speakerdeck.com/mgechev/introduction-to-angular-2
      flag: ğŸ‡§ğŸ‡¬
    - title: "Code Reusability in Angular"
      event: Angular Berlin, Berlin, Germany
      date: 10th of June, 2015
      slides: https://speakerdeck.com/mgechev/code-reusability-in-angular
      flag: ğŸ‡©ğŸ‡ª
    - title: "Bringing Immutability to Angular"
      event: ng-vegas, Las Vegas, USA
      date: 7th of May, 2015
      video: https://www.youtube.com/watch?v=zeChCjj-tbY
      flag: ğŸ‡ºğŸ‡¸
    - title: "AngularJS in Patterns"
      event: AngularJS-SF user group, San Francisco, USA
      date: 25th of February, 2015
      slides: https://speakerdeck.com/mgechev/angularjs-in-patterns-lightning-talk
      flag: ğŸ‡ºğŸ‡¸
    - title: "Taking the web apps offline"
      event: jQuery Sofia, Sofia, Bulgaria
      date: 27th of January, 2015
      slides: https://speakerdeck.com/mgechev/taking-the-web-apps-offline
      flag: ğŸ‡§ğŸ‡¬
    - title: "Lightweight AngularJS"
      event: SoftServe's IT Weekend, Sofia, Bulgaria
      date: 29th of November, 2014
      slides: https://speakerdeck.com/mgechev/lightweight-angularjs
      flag: ğŸ‡§ğŸ‡¬
    - title: "Introduction to JavaScriptâ€™s MVW with Backbone.js"
      event: HackBulgaria, Sofia, Bulgaria
      date: 31st of July, 2014
      slides: https://speakerdeck.com/mgechev/introduction-to-mvw-in-javascript
      flag: ğŸ‡§ğŸ‡¬
    - title: "Introduction to WebRTC"
      event: JSNext, Sofia, Bulgaria
      date: 24th of November, 2014
      slides: https://github.com/mgechev/webrtc-slides-jsnext
      flag: ğŸ‡§ğŸ‡¬
    - title: "What can JavaScript do?"
      event: HackBulgaria, Sofia, Bulgaria
      date: 31st of October, 2014
      slides: https://github.com/mgechev/what-js-can-do-slides
      flag: ğŸ‡§ğŸ‡¬
    - title: "AngularJS in Patterns"
      event: PlovDev, Plovdiv, Bulgaria
      date: 18th of October, 2014
      slides: https://github.com/mgechev/angularjs-in-patterns-slides-plovdev
      flag: ğŸ‡§ğŸ‡¬
    - title: "Aspect-Oriented Programming with AngularJS"
      event: AngularJS-SF user group, San Francisco, USA
      date: 5th of May, 2014
      slides: https://github.com/mgechev/angular-aop-talk
      flag: ğŸ‡ºğŸ‡¸
    - title: "Single-Page Applications Ğ¸ AngularJS (BG)"
      event: OpenFest, Sofia, Bulgaria
      date: 9th of November, 2013
      video: https://www.youtube.com/watch?v=G35xa-LuR8Q
      flag: ğŸ‡§ğŸ‡¬
    - title: "JavaScript Patterns (BG)"
      event: Telerik, Sofia, Bulgaria
      date: 22nd of April, 2013
      video: https://www.youtube.com/watch?v=a23oYdqQVvM
      flag: ğŸ‡§ğŸ‡¬

social:
  twitter: "https://twitter.com/mgechev"
  github: "https://github.com/mgechev"
  stack-overflow: "https://stackoverflow.com/users/1106382/minko-gechev"
