baseURL: http://blog.mgechev.com/
disablePathToLower: true
languageCode: en-us
title: Minko Gechev's blog
googleAnalytics: "UA-18060688-3"
theme: "minimalist"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsUseClasses: true

outputFormats:
  RSS:
    baseName: "feed"

params:
  bio: "Co-founder & CTO at <a href=\"https://rhyme.com\">Rhyme.com</a>"
  description: "Articles about computer science, Angular, JavaScript, and compilers."
  author: "Minko Gechev"
  twitter: mgechev
  enableRSS: true
  enableGoogleAnalytics: true
  enableDisqus: true
  disqusShortname: mgechev
  socialIconStyle: ""
  iconFont: "font-awesome"
  archive: "Posts"

  talks:
    - title: "Mad Science with the Angular Compiler"
      description: <a href="https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler">slides</a>
        (Dreamix, Sofia, Bulgaria, 12th of January, 2018)
      link: https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler
      flag: ğŸ‡§ğŸ‡¬
    - title: "Faster Angular Applications"
      description: <a href="https://holyjs-moscow.ru/en/talks/3hmyldgekuymaycqcykq60/">HolyJS</a> (Moscow,
        Russia, 10th of December, 2017)
      link: https://speakerdeck.com/mgechev/faster-angular-applications
      flag: ğŸ‡·ğŸ‡º
    - title: "Angular Performance Checklist"
      description: <a href="http://ng-colombia.org/">NG-COLOMBIA</a> (online,
        18th of November, 2017)
      link: https://speakerdeck.com/mgechev/purely-fast
      flag: ğŸ‡¨ğŸ‡´
    - title: "Fast & /Fu(nctional|rious)/"
      description: <a href="https://tesla.com/">Tesla Motors</a> (California, United States,
        15th of November, 2017)
      link: /talks/
      flag: ğŸ‡ºğŸ‡¸
    - title: "Purely Fast"
      description: <a href="https://www.angularconnect.com/">AngularConnect</a> (London, United Kingdom,
        7th of November, 2017)
      link: https://speakerdeck.com/mgechev/purely-fast
      flag: ğŸ‡¬ğŸ‡§
    - title: "Angular Performance Checklist"
      description: <a href="https://bayfest2017.com/">Bay Fest</a> (San Francisco, California,
        28th of October, 2017)
      link: https://speakerdeck.com/mgechev/angular-performance-checklist-1
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular Performance Checklist"
      description: <a href="https://angulardevsummit.com/">Angular Dev Summit</a> (online,
        11th of September, 2017)
      link: https://speakerdeck.com/mgechev/angular-performance-checklist-1
      flag: ğŸŒ
    - title: "Angular Performance Checklist"
      description: ngHouston (online, 18th of August, 2017)
      link: https://speakerdeck.com/mgechev/angular-performance-checklist-1
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular Unplugged Q&A session"
      description: Q&amp;A session organized for the Bulgarian JavaScript community, <a
        href="https://speakerdeck.com/mgechev/angular-unplugged">slides</a> (Sofia, Bulgaria,
        13th of July, 2017)
      link: https://speakerdeck.com/mgechev/angular-unplugged
      flag: ğŸ‡§ğŸ‡¬
    - title: "Mad Science with the Angular Compiler"
      description: <a href="https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler">slides</a>
        (AngularUP, Tel Aviv, Israel, 25th of June, 2017)
      link: https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler
      flag: ğŸ‡®ğŸ‡±
    - title: "Angular Performance Checklist"
      description: ngcruise (cruise ship, Bahamas, 31st May, 2017)
      link: https://speakerdeck.com/mgechev/angular-performance-checklist-1
      flag: ğŸ‡§ğŸ‡¸
    - title: "Mad Science with the Angular Compiler"
      description: Angular Bolivia (online, 30th of April, 2017)
      link: https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler
      flag: ğŸ‡§ğŸ‡´
    - title: "Mad Science with the Angular Compiler"
      description: <a href="https://www.youtube.com/watch?v=tBV4IQwPssU">video (en)</a>,
        ng-conf (Salt Lake City, Utah, 5th of April, 2017)
      link: https://speakerdeck.com/mgechev/mad-science-with-the-angular-compiler
      flag: ğŸ‡ºğŸ‡¸
    - title: "Linting Angular"
      description: Modern Web (Mountain View, California, 9th of March 2017)
      link: https://speakerdeck.com/mgechev/linting-angular-1
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular as Integrated Development Platform"
      description: Angular Sofia (Sofia, Bulgaria, 12th of January 2017)
      link: https://speakerdeck.com/mgechev/angular-as-integrated-development-platform
      flag: ğŸ‡§ğŸ‡¬
    - title: "Scalable Application Architecture"
      description: ng-be (Ghent, Belgium, 9th of December 2016)
      link: https://speakerdeck.com/mgechev/scalable-application-architecture
      flag: ğŸ‡§ğŸ‡ª
    - title: "Building Angular App for Production"
      description: Angular Orange County (Google, Orange County, 10th of November 2016),
        SoCal CodeCamp (USC, Los Angeles, 12th of November 2016)
      link: https://speakerdeck.com/mgechev/building-an-angular-app-for-production
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular Toolset Support"
      description: Connect.Tech (Atlanta, Georgia, 22nd of October 2016)
      link: https://speakerdeck.com/mgechev/angular-toolset-support
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular Performance Checklist"
      description: Connect.Tech (Atlanta, Georgia, 21st of October 2016)
      link: https://speakerdeck.com/mgechev/angular-performance-checklist
      flag: ğŸ‡ºğŸ‡¸
    - title: "Linting Angular"
      description: South Bay JavaScript (Mountain View, California, 12th of October 2016)
      link: https://speakerdeck.com/mgechev/linting-angular
      flag: ğŸ‡ºğŸ‡¸
    - title: "Angular 2 Toolset Support"
      description: Capgemini Webinar (online, 26th of May, 2016)
      link: https://speakerdeck.com/mgechev/angular-2-toolset-support
      flag: ğŸ‡®ğŸ‡³
    - title: "Integrated Web Stack with Angular 2"
      description: xlr8con (Sofia, Bulgaria, 14th of May, 2016)
      link: https://speakerdeck.com/mgechev/integrated-web-stack-with-angular-2
      flag: ğŸ‡§ğŸ‡¬
    - title: "Automated Angular 2 Style Checking with Codelyzer"
      description: ng-conf (Salt Lake City, Utah, United States, 6th of May, 2016)
      link: https://youtu.be/bci-Z6nURgE
      flag: ğŸ‡ºğŸ‡¸
    - title: "Scalable Angular 2 Application Architecture"
      description: FDConf (Minsk, Belarus, 16th of April, 2016)
      link: https://speakerdeck.com/mgechev/scalable-angular-2-application-architecture
      flag: ğŸ‡§ğŸ‡¾
    - title: "Angular 2 - Quick Web Start"
      description: "Angular 2 â¤ NativeScript (Sofia, Bulgaria, 10th of March, 2016)"
      link: https://speakerdeck.com/mgechev/angular-2-quick-web-start
      flag: ğŸ‡§ğŸ‡¬
    - title: "Building Universal Applications with Angular 2"
      description: OpenFest 2015 (Sofia, Bulgaria), ITWeekend 2015 (Sofia, Bulgaria),
        JSTalks 2015 (Sofia, Bulgaria).
      link: https://speakerdeck.com/mgechev/building-universal-applications-with-angular-2
      flag: ğŸ‡§ğŸ‡¬
    - title: "Cutting Angularâ€™s Crosscuts"
      description: <a href="https://www.youtube.com/watch?v=C6e6-31HD5A">video (en)</a>,
        AngularConnect (London, United Kingdom, 21st of October, 2015)
      link: https://speakerdeck.com/mgechev/cutting-angulars-crosscuts
      flag: ğŸ‡¬ğŸ‡§
    - title: "Immutable.js with Angular"
      description: <a href="http://angular-air.com/">AngularAir Podcast</a> (online, 22nd
        of September, 2015)
      link: https://www.youtube.com/watch?v=gN1K1hE9v4g
      flag: ğŸŒ
    - title: "Single-Page Applications: Challenges"
      description: <a href="http://ukraine.itweekend.ua/en/">IT Weekend</a> (Kiev, Ukraine,
        12th of September, 2015)
      link: https://speakerdeck.com/mgechev/single-page-applications-challenges
      flag: ğŸ‡ºğŸ‡¦
    - title: "Bringing Immutability to Angular"
      description: <a href="http://frontendweekend.uwcua.com/">Front-end Weekend</a> (online,
        16th of August, 2015)
      link: https://speakerdeck.com/mgechev/bringing-immutability-to-angular
      flag: ğŸŒ
    - title: "Immutability with Angular with Minko Gechev"
      description: <a href="http://adventuresinangular.com/">Adventures in Angular Podcast</a>
        (online, 29th of July, 2015)
      link: http://devchat.tv/adventures-in-angular/054-aia-immutability-with-angular-with-minko-gechev
      flag: ğŸŒ
    - title: "Introduction to Angular 2"
      description: Webloz Edge (Burgas, Bulgaria, 29th of June, 2015)
      link: https://speakerdeck.com/mgechev/introduction-to-angular-2
      flag: ğŸ‡§ğŸ‡¬
    - title: "Code Reusability in Angular"
      description: Angular Berlin (Berlin, Germany, 10th of June, 2015)
      link: https://speakerdeck.com/mgechev/code-reusability-in-angular
      flag: ğŸ‡©ğŸ‡ª
    - title: "Bringing Immutability to Angular"
      description: ng-vegas (Las Vegas, USA, 7th of May, 2015)
      link: https://www.youtube.com/watch?v=zeChCjj-tbY
      flag: ğŸ‡ºğŸ‡¸
    - title: "AngularJS in Patterns"
      description: AngularJS-SF user group (San Francisco, USA, 25th of February, 2015)
      link: https://speakerdeck.com/mgechev/angularjs-in-patterns-lightning-talk
      flag: ğŸ‡ºğŸ‡¸
    - title: "Taking the web apps offline"
      description: talk I did in ICN (Sofia, Bulgaria, 27th of January, 2015)
      link: https://speakerdeck.com/mgechev/taking-the-web-apps-offline
      flag: ğŸ‡§ğŸ‡¬
    - title: "Lightweight AngularJS"
      description: SoftServeâ€™s IT Weekend (Sofia, Bulgaria, 29th of November, 2014). Blog
        post on this topic could be <a href="https://github.com/mgechev/light-angularjs">found
        here</a>
      link: https://speakerdeck.com/mgechev/lightweight-angularjs
      flag: ğŸ‡§ğŸ‡¬
    - title: "Introduction to JavaScriptâ€™s MVW with Backbone.js"
      description: HackBulgaria (Sofia, Bulgaria, 31st of July, 2014)
      link: https://speakerdeck.com/mgechev/introduction-to-mvw-in-javascript
      flag: ğŸ‡§ğŸ‡¬
    - title: "Introduction to WebRTC"
      description: JSNext, (Sofia, Bulgaria, 24th of November, 2014)
      link: https://github.com/mgechev/webrtc-slides-jsnext
      flag: ğŸ‡§ğŸ‡¬
    - title: "What can JavaScript do?"
      description: HackBulgaria (Sofia, Bulgaria, 31st of October, 2014)
      link: https://github.com/mgechev/what-js-can-do-slides
      flag: ğŸ‡§ğŸ‡¬
    - title: "AngularJS in Patterns"
      description: PlovDev (Plovdiv, Bulgaria, 18th of October, 2014)
      link: https://github.com/mgechev/angularjs-in-patterns-slides-plovdev
      flag: ğŸ‡§ğŸ‡¬
    - title: "Aspect-Oriented Programming with AngularJS"
      description: AngularJS-SF user group (San Francisco, USA, 5th of May, 2014)
      link: https://github.com/mgechev/angular-aop-talk
      flag: ğŸ‡ºğŸ‡¸
    - title: "Single-Page Applications Ğ¸ AngularJS (BG)"
      description: OpenFest (Sofia, Bulgaria, 9th of November, 2013).
      link: https://www.youtube.com/watch?v=G35xa-LuR8Q
      flag: ğŸ‡§ğŸ‡¬
    - title: "JavaScript Patterns (BG)"
      description: Telerik (Sofia, Bulgaria, 22nd of April, 2013)
      link: https://www.youtube.com/watch?v=a23oYdqQVvM
      flag: ğŸ‡§ğŸ‡¬



social:
  twitter: "https://twitter.com/mgechev"
  github: "https://github.com/mgechev"
  stack-overflow: "https://stackoverflow.com/users/1106382/minko-gechev"
